spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/jetdevs_test?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:}
    dbcp2:
      max-wait-millis: 30000
      validation-query: /* ping */ select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
springdoc:
  pathsToMatch: /api/**
